"""
WildlyPlay Loop #3: AI-Citation & Search Monitor
Weekly cron — pulls GSC data, tracks brand visibility, reports to Telegram.
Usage: python3 scripts/wp-citation-monitor.py
"""
import json
import os
import sys
from datetime import datetime, timedelta, UTC

from google.oauth2 import service_account
from googleapiclient.discovery import build

SA_PATH = os.path.expanduser("~/.config/claude-seo/wildlyplay-service-account.json")
SITE_URL = "sc-domain:wildlyplay.com"

SCOPES = ["https://www.googleapis.com/auth/webmasters.readonly"]

def get_gsc_service():
    creds = service_account.Credentials.from_service_account_file(SA_PATH, scopes=SCOPES)
    return build("searchconsole", "v1", credentials=creds)

def query_performance(service, start, end, dimensions=None, row_limit=25):
    body = {
        "startDate": start,
        "endDate": end,
        "dimensions": dimensions or ["query"],
        "rowLimit": row_limit,
    }
    return service.searchanalytics().query(siteUrl=SITE_URL, body=body).execute()

def main():
    service = get_gsc_service()

    end = (datetime.now(UTC) - timedelta(days=3)).strftime("%Y-%m-%d")
    start_7d = (datetime.now(UTC) - timedelta(days=10)).strftime("%Y-%m-%d")
    start_28d = (datetime.now(UTC) - timedelta(days=31)).strftime("%Y-%m-%d")

    # 1. Overall performance (7 days)
    overall = query_performance(service, start_7d, end, dimensions=["date"], row_limit=10)
    total_clicks = sum(r.get("clicks", 0) for r in overall.get("rows", []))
    total_impressions = sum(r.get("impressions", 0) for r in overall.get("rows", []))
    avg_ctr = (total_clicks / total_impressions * 100) if total_impressions > 0 else 0
    avg_pos = 0
    if overall.get("rows"):
        avg_pos = sum(r.get("position", 0) for r in overall["rows"]) / len(overall["rows"])

    # 2. Top queries (28 days)
    queries = query_performance(service, start_28d, end, dimensions=["query"], row_limit=15)
    top_queries = queries.get("rows", [])

    # 3. Brand queries (mentions of "wildlyplay")
    brand_queries = [q for q in top_queries if "wildlyplay" in q["keys"][0].lower()]

    # 4. Top pages (7 days)
    pages = query_performance(service, start_7d, end, dimensions=["page"], row_limit=10)
    top_pages = pages.get("rows", [])

    # 5. Index coverage check
    try:
        inspection_available = True
        # URL Inspection API — check key pages
        key_urls = [
            "https://www.wildlyplay.com/",
            "https://www.wildlyplay.com/transparency",
            "https://www.wildlyplay.com/guides",
            "https://www.wildlyplay.com/archive",
        ]
        indexed_count = 0
        not_indexed = []
        for url in key_urls:
            try:
                result = service.urlInspection().index().inspect(
                    body={"inspectionUrl": url, "siteUrl": SITE_URL}
                ).execute()
                verdict = result.get("inspectionResult", {}).get("indexStatusResult", {}).get("verdict", "UNKNOWN")
                if verdict == "PASS":
                    indexed_count += 1
                else:
                    not_indexed.append(f"{url} ({verdict})")
            except Exception:
                not_indexed.append(f"{url} (check failed)")
    except Exception:
        inspection_available = False

    # Format report
    lines = [
        "<b>📊 WildlyPlay Search Monitor — Weekly</b>",
        f"Period: {start_7d} → {end}",
        "",
        "<b>Performance (7d):</b>",
        f"• Clicks: {total_clicks}",
        f"• Impressions: {total_impressions:,}",
        f"• CTR: {avg_ctr:.1f}%",
        f"• Avg position: {avg_pos:.1f}",
        "",
    ]

    if brand_queries:
        lines.append("<b>Brand queries:</b>")
        for q in brand_queries:
            lines.append(f"• \"{q['keys'][0]}\" — {q.get('clicks', 0)} clicks, pos {q.get('position', 0):.1f}")
        lines.append("")
    else:
        lines.append("Brand queries: none yet (site is new)")
        lines.append("")

    if top_queries:
        lines.append("<b>Top queries (28d):</b>")
        for q in top_queries[:8]:
            lines.append(f"• \"{q['keys'][0]}\" — {q.get('clicks', 0)}c / {q.get('impressions', 0)}i / pos {q.get('position', 0):.1f}")
        lines.append("")

    if top_pages:
        lines.append("<b>Top pages (7d):</b>")
        for p in top_pages[:5]:
            url = p["keys"][0].replace("https://www.wildlyplay.com", "")
            lines.append(f"• {url or '/'} — {p.get('clicks', 0)}c / {p.get('impressions', 0)}i")
        lines.append("")

    if inspection_available:
        lines.append(f"<b>Index status:</b> {indexed_count}/{len(key_urls)} key pages indexed")
        if not_indexed:
            for ni in not_indexed:
                lines.append(f"⚠️ {ni}")
        lines.append("")

    lines.append("🤖 Auto-generated by Loop #3 monitor")

    report = "\n".join(lines)
    print(report)

if __name__ == "__main__":
    main()
